#cloud-config

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0644
    # strenghten SSH cyphers
    content: |
      Port 22
      Protocol 2
      HostKey /etc/ssh/ssh_host_ed25519_key
      KexAlgorithms curve25519-sha256@libssh.org
      Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
      MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
      UsePrivilegeSeparation yes
      KeyRegenerationInterval 3600
      ServerKeyBits 1024
      SyslogFacility AUTH
      LogLevel INFO
      LoginGraceTime 120
      PermitRootLogin prohibit-password
      StrictModes yes
      RSAAuthentication yes
      PubkeyAuthentication yes
      IgnoreRhosts yes
      RhostsRSAAuthentication no
      HostbasedAuthentication no
      PermitEmptyPasswords no
      ChallengeResponseAuthentication no
      PasswordAuthentication no
      X11Forwarding yes
      X11DisplayOffset 10
      PrintMotd no
      PrintLastLog yes
      TCPKeepAlive yes
      AcceptEnv LANG LC_*
      Subsystem sftp /usr/lib/openssh/sftp-server
      UsePAM yes


apt:
  sources:
    docker.list:
      source: "deb https://download.docker.com/linux/ubuntu xenial stable"
      keyserver: p80.pool.sks-keyservers.net
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

#This will be triggered automatically by adding another apt source
#apt_update: true
#This we'll do ourselves - TODO: check if it does a dist-upgrade
#apt_upgrade: true

packages:
  - docker-ce
  - tmux
  - htop
  - vim
  - fail2ban
  - curl
  - jq

# note that we're treating this YAML file as a template with $${VARIABLE} substitution
runcmd:
  - usermod -G docker ${SSH_USER}
  - systemctl enable docker
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
  - DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
  - systemctl start docker
  - docker run -d --restart=always redis:3.2
  - reboot